### ISSUE TITLE
[Request] Svelte Icon

### ISSUE THREAD

**Issue by MatthiasGrandl** [yamatsum/nonicons#14]
https://svelte.dev/
https://svelte.dev/svelte-logo-horizontal.svg

Svelte is a pretty popular framework by now and it looks like a lot of people in the vim community are using it, so it would be cool to have a nice icon :)

**Comment by yamatsum** [comment]
@MatthiasGrandl Added svelte icon! Enjoy the new nonicons!
<img width="106" alt="CleanShot 2021-08-31 at 15 49 50@2x" src="https://user-images.githubusercontent.com/42740055/131456115-e8a46797-c1b4-4651-8f95-aaa21b1c7636.png">

**Comment by MatthiasGrandl** [comment]
@yamatsum very nice thank you so much!
