### ISSUE TITLE
Please support vscode

### ISSUE THREAD

**Issue by ippo012** [yamatsum/nonicons#2]
Hi, nonicons is very cool set of icons.
I'd like to use it with vscode, so I'd like you to make an extension for it.

**Comment by yamatsum** [comment]
https://github.com/yamatsum/vscode-nonicons
enjyo it!

**Comment by yamatsum** [comment]
![CleanShot 2022-05-09 at 16 20 38@2x](https://user-images.githubusercontent.com/42740055/167360028-5152f225-cfb8-4181-a7d5-176000ad9b65.png)

**Comment by yamatsum** [comment]
![CleanShot 2022-05-09 at 16 24 24@2x](https://user-images.githubusercontent.com/42740055/167360615-7e9d9204-9874-4042-9914-a07da39aaf53.png)

**Comment by yamatsum** [comment]
![CleanShot 2022-05-09 at 16 35 03@2x](https://user-images.githubusercontent.com/42740055/167362197-a6c9d9fc-60a7-4049-b843-fe93676752ac.png)

**Comment by lfom** [comment]
> ![CleanShot 2022-05-09 at 16 35 03@2x](https://user-images.githubusercontent.com/42740055/167362197-a6c9d9fc-60a7-4049-b843-fe93676752ac.png)

@yamatsum The last screenshot is also VSCode? Could you please explain what you did to get the statusbar looking like that, perhaps link to a guide? I searched online and could not find anything like this. Thank you!
