### ISSUE TITLE
Icons are no longer vertically centered in terminal

### ISSUE THREAD

**Issue by HumblePresent** [yamatsum/nonicons#25]
As of commit 2644552 the icons are no longer vertically centered within a cell in a terminal emulator.

### Sample icon on commit 598b1bc:
![nonicons_good](https://user-images.githubusercontent.com/60856003/151290582-c42fdd30-4c22-4af5-b48a-09f912e314fb.png)

### Sample icon on commit 2644552:
![nonicons_bad](https://user-images.githubusercontent.com/60856003/151290614-bc1addb8-9350-4b7d-baf6-cf704d336f0f.png)

These images were captured running
* Neovim: NVIM v0.6.0-dev+642-g07223fae5
* kitty 0.24.1
* nonicons.ttf

As you can see, in the first image the Lua icon is vertically centered within the terminal cell but in the second it is aligned to the top of the cell.

**Comment by yamatsum** [comment]
https://github.com/yamatsum/nonicons/issues/22

**Comment by HumblePresent** [comment]
The alignment is corrected with the latest commit. Thanks!
