### ISSUE TITLE
GraphQL(`.gql`) Icon is not displayed

### ISSUE THREAD

**Issue by ogakuzuko** [yamatsum/nonicons#27]
It seems that `.gql` icon is not displayed.

<img width="158" alt="CleanShot 2022-02-23 at 22 35 03@2x" src="https://user-images.githubusercontent.com/70119474/155330359-7e514932-452f-4899-8adc-89c1b48dbb99.png">

However, `.graphql` seems to be displayed.

<img width="194" alt="CleanShot 2022-02-23 at 22 34 27@2x" src="https://user-images.githubusercontent.com/70119474/155330471-db222db4-5e24-4b45-a23c-64f272efac71.png">

If you need any additional information, please reply.

Thank you for the beautiful icon! :)

**Comment by yamatsum** [comment]
@ogakuzuko 
Supported in [v0.0.11](https://marketplace.visualstudio.com/items?itemName=yamatsum.vscode-nonicons)
Try to update
