### ISSUE TITLE
Feature Request: Terraform icon

### ISSUE THREAD

**Issue by cappyzawa** [yamatsum/nonicons#7]
Thank you for your cool icons.

Can you add the terraform icon as well, please?

References
* [Terraform by HashiCorp](https://www.terraform.io/)
* [Terraform logo](https://www.hashicorp.com/brand#terraform)

**Comment by yamatsum** [comment]
https://github.com/yamatsum/nonicons/commit/ca15fd447824a37c34ea95d10e490ae0eac6967c
enjoy it!
