### ISSUE TITLE
Feature Request: Add to the AUR

### ISSUE THREAD

**Issue by cooper-anderson** [yamatsum/nonicons#8]
It would be really nice to have nonicons available from the AUR on Arch and Arch-based Linux distros. It would make updating whenever a new version comes out seamless.

**Comment by hapakaien** [comment]
> It would be really nice to have nonicons available from the AUR on Arch and Arch-based Linux distros. It would make updating whenever a new version comes out seamless.

You can try [this AUR package](https://aur.archlinux.org/packages/nonicons-font/). Actually, I just created this package. 
If you find a bug, you alwayas send PR to https://github.com/official-human/nonicons-font

**Comment by cooper-anderson** [comment]
👍
